defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
    disqus:
      shorname: dlbewleygithubio

permalink: /blog/:year/:month/:day/:title
pygments: true

site:
  - url: "//dlbewley.github.io/"
