defaults:
  # everything
  - scope:
      path: "" # all files
    values:
      layout: "slate"
      author:
        name: Dale Bewley
        email: dale@bewley.net
      disqus:
        shortname: dlbewleygithubio
        enabled: false

  # posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      disqus:
        enabled: true

permalink: /blog/:year/:month/:day/:title

#pygments: true

collections:
  drafts:
    layout: "draft"

site:
  url: "//guifreelife.com/"
# Includes an icon in the footer for each user name you enter
footer_links:
  github: dlbewley
  twitter: dlbewley
  linkedin: 60564658
  facebook: dale.bewley
  youtube: DaleBewley
  googleplus: +DaleBewley
