defaults:
  # everything
  - scope:
      path: "" # all files
    values:
      layout: "slate"
      author:
        name: Dale Bewley
        email: dale@bewley.net
      disqus:
        shortname: dlbewleygithubio
        enabled: false
      google:
        analytics: "UA-78084690-1"

  # posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      disqus:
        enabled: true

permalink: /blog/:year/:month/:day/:title

collections:
  drafts:
    layout: "draft"

site:
  url: "//guifreelife.com/"
# Includes an icon in the footer for each user name you enter
footer_links:
  github: dlbewley
  twitter: dlbewley
  linkedin: dalebewley
  facebook: dale.bewley
  youtube: DaleBewley

plugins:
  - jekyll-feed
    description: The GUI Free Life and times of Dale Bewley. A blog on topics such as Linux, Networking, and Kubernetes.
