defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      disqus:
        shortname: dlbewleygithubio
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Dale Bewley"

permalink: /blog/:year/:month/:day/:title

pygments: true

# http://dafoster.net/projects/rdiscount/
markdown: rdiscount

#site:
#  - url: "//dlbewley.github.io/"
