defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      disqus:
        shortname: dlbewleygithubio
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Dale Bewley"
      disqus:
        enabled: true

permalink: /blog/:year/:month/:day/:title

#pygments: true

markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# http://dafoster.net/projects/rdiscount/
#markdown: rdiscount

#site:
#  - url: "//dlbewley.github.io/"
