defaults:
  - scope:
      path: "" # all files
    values:
      layout: "slate"
      author:
        name: Dale Bewley
        email: dale@bewley.net


#      disqus:
#        shortname: dlbewleygithubio
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"
#      disqus:
#        enabled: true
#

permalink: /blog/:year/:month/:day/:title

pygments: true
#markdown: redcarpet2
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

site:
  url: "//dlbewley.github.io/"
